### ISSUE TITLE
Styleguide is not consistent on this page  in ./help/introduction.md for zh-tw

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/contributor.zh-Hant#1]
Issue in ./help/introduction.md

Styleguide is not consistent on this page
step1, the UI option is left in english (while actual UI is localized)
and then in step2, the UI option translation became English UI plus translation in brackets style

Overall style is mixed. Also, actual Ui was translated but translators still use english UI in translated page...

**Comment by adobechienan** [comment]
Thank you. We are looking into this issue.

**Comment by adobechienan** [comment]
Thank you for your feedback. This is being reviewed and tracked in G11N-12131.

**Comment by adobechienan** [comment]
Please note that this issue should now be resolved.
